groups:
- name: Instance alerts
  rules:  

  - alert: InstanceDown
    expr: up == 0
    for: 1m
    labels:
      severity: 'critical'
    annotations:
      host: "{{ $labels.job }} ({{ $labels.instance }})"
      summary: "Instance {{ $labels.job }} ({{ $labels.instance }}) is down"

  - alert: CPUUtilization70%
    expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 70
    for: 2m
    labels:
      severity: 'warning'
    annotations:
      host: "{{ $labels.job }} ({{ $labels.instance }})"
      summary: "CPU Utilization exceeds 70% on {{ $labels.job }} ({{ $labels.instance }})"

  - alert: CPUUtilization85%
    expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 85
    for: 2m
    labels:
      severity: 'critical'
    annotations:
      host: "{{ $labels.job }} ({{ $labels.instance }})"
      summary: "CPU Utilization exceeds 85% on {{ $labels.job }} ({{ $labels.instance }})"

  - alert: MemoryUtilization70%
    expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 30
    for: 2m
    labels:
      severity: 'warning'
    annotations:
      host: "{{ $labels.job }} ({{ $labels.instance }})"
      summary: "Memory Utilization exceeds 70% on {{ $labels.job }} ({{ $labels.instance }})"

  - alert: MemoryUtilization85%
    expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 15
    for: 2m
    labels:
      severity: 'critical'
    annotations:
      host: "{{ $labels.job }} ({{ $labels.instance }})"
      summary: "Memory Utilization exceeds 85% on {{ $labels.job }} ({{ $labels.instance }})"

  - alert: DiskUtilization70%
    expr: (node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes < 30 and ON (instance, device, mountpoint) node_filesystem_readonly == 0
    for: 2m
    labels:
      severity: 'warning'
    annotations:
      host: "{{ $labels.job }} ({{ $labels.instance }})"
      summary: "Disk Utilization exceeds 70% on {{ $labels.job }} ({{ $labels.instance }})"

  - alert: DiskUtilization85%
    expr: (node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes < 15 and ON (instance, device, mountpoint) node_filesystem_readonly == 0
    for: 2m
    labels:
      severity: 'critical'
    annotations:
      host: "{{ $labels.job }} ({{ $labels.instance }})"
      summary: "Disk Utilization exceeds 85% on {{ $labels.job }} ({{ $labels.instance }})"



