global:
  resolve_timeout: 1m

route:
  receiver: email
  routes:
   - match:
      severity: warning
     receiver: email
     group_wait: 30s
     group_interval: 5m
     repeat_interval: 30m
   
   - match:
      severity: critical
     receiver: email
     group_wait: 30s
     group_interval: 5m
     repeat_interval: 30m

receivers:
  - name: email
    email_configs:
      - to: <TO_EMAIL>
        from: <FROM_EMAIL>
        smarthost: smtp.gmail.com:587
        auth_username: <FROM_EMAIL>
        auth_password: <APP_PASSWORD_OF_FROM_EMAIL>
        html: '{{ template "email" .}}'
        send_resolved: true

templates:
- 'alert.tmpl'